---
output:
html_document: default
'html_document: rep_research_1': default
---

```{r setup, include=FALSE}
require(knitr)
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r echo=FALSE, results='hide', warning=FALSE, message=FALSE}
#Loading and preprocessing the data
unzip("activity.zip", files="activity.csv")
activity <- read.csv("activity.csv")
head(activity)
str(activity)
```

```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
#What is mean total number of steps taken per day?
activity <- transform(activity, date = as.Date(date))
str(activity)
activity.NoNAs <- activity[complete.cases(activity),]
totalStepsPerDay <- aggregate(steps ~ date, activity.NoNAs, sum)
require(ggplot2)
g <- ggplot(totalStepsPerDay, aes(x=steps)) +
geom_histogram(alpha=0.5, fill="red", binwidth=1000,position='identity') +
ylab("Frequency") + xlab("Total number of steps per day") +
ggtitle("Histogram of the total number of steps taken per day")
g
```
```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
#What is the average daily activity pattern?
mean(totalStepsPerDay$steps)
median(totalStepsPerDay$steps)
avgStepInterval <- aggregate(steps ~ interval, activity, mean) 
avgStepInterval$time <- formatC(avgStepInterval$interval, width = 4, format = "d", flag = "0") 
avgStepInterval$time <- strptime(avgStepInterval$time, format = "%H%M")
str(avgStepInterval)
require(scales)
g <- ggplot(avgStepInterval, aes(x = time, y = steps)) +
geom_line(colour = "blue") +
scale_x_datetime(labels = date_format("%H:%M")) +
xlab("Interval") +
ylab("Average number of steps") +
ggtitle("Average number of steps taken versus time interval") + 
geom_vline(xintercept = as.numeric(as.POSIXct(
avgStepInterval[which.max(avgStepInterval$steps), "time"]
)), color = "red", linetype = "dashed")
g
```
```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
maxStepsInterval <- avgStepInterval[which.max(avgStepInterval$steps), "interval"]
maxStepsInterval
maxStepsInterval <- avgStepInterval[which.max(avgStepInterval$steps), "time"]
format(maxStepsInterval, "%H:%M")
sum(is.na(activity))
# Calculate the number of steps per interval averaged over all days; this is the replacement data:
replacements <- aggregate(steps ~ interval, activity, mean, na.action = na.omit)$steps
activity.imputed <- transform(activity, steps = ifelse(is.na(activity$steps), replacements, activity$steps))
sum(is.na(activity.imputed))
head(activity.imputed)
totalStepsPerDay.imputed <- aggregate(steps ~ date, activity.imputed, sum)
g <- ggplot(totalStepsPerDay.imputed, aes(x=steps)) +
geom_histogram(alpha=0.5, fill="skyblue", binwidth=1000,position='identity') +
ylab("Frequency") + xlab("Total number of steps per day") +
ggtitle("Histogram of the total number of steps taken per day")
g
```
```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
mean(totalStepsPerDay.imputed$steps)
median(totalStepsPerDay.imputed$steps)
g <- ggplot(totalStepsPerDay, aes(x=steps)) +
geom_histogram(data = totalStepsPerDay, alpha=0.5, fill="red", binwidth=1000,position='identity') +
geom_histogram(data = totalStepsPerDay.imputed, alpha=0.5, fill="skyblue", binwidth=1000,position='identity') +
ylab("Frequency") + xlab("Total number of steps per day") +
ggtitle("Histogram of the total number of steps taken per day")
g
```
```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
activity.imputed$day <- weekdays(activity.imputed$date)
# Does the day begin with an 's'?
activity.imputed$isWeekend <- grepl("^S", activity.imputed$day)
activity.imputed$dayType <- factor(activity.imputed$isWeekend, levels = c(F, T), labels = c("Weekday", "Weekend"))
head(activity.imputed)
str(activity.imputed)
g <- ggplot(avgStepInterval$imputed, aes(x = time, y = steps)) +
facet_grid(dayType ~ .) +
geom_line(colour = "blue") +
scale_x_datetime(labels = date_format("%H:%M")) +
xlab("Interval") +
ylab("Average number of steps") +
ggtitle("Average number of steps taken versus time interval") 
```

```{r echo=TRUE, results='hide', warning=FALSE, message=FALSE}
averageStepsPerInterval.imputed <- aggregate(steps ~ interval + dayType, activity.imputed, mean)
# Firstly, transform the interval data (integers) into characters padded with leading zeros as needed:
averageStepsPerInterval.imputed$time <- formatC(averageStepsPerInterval.imputed$interval, width = 4, format = "d", flag = "0")
# Next, convert the character representation of the time into an actual time:
averageStepsPerInterval.imputed$time <- strptime(averageStepsPerInterval.imputed$time, format = "%H%M")
g <- ggplot(averageStepsPerInterval.imputed, aes(x = time, y = steps)) +
facet_grid(dayType ~ .) +
geom_line(colour = "blue") +
scale_x_datetime(labels = date_format("%H:%M")) +
xlab("Interval") +
ylab("Average number of steps") +
ggtitle("Average number of steps taken versus time interval") 
g
```
